#!/usr/bin/env python3
"""Cut the offline suite's fixtures out of real captures, and PROVE they parse
the same.

Its output is `fixtures_generated.json`, which `smoke_test.py` loads.

WHY A GENERATED FILE RATHER THAN INLINE LITERALS
------------------------------------------------
The family's rule is fixtures inline in `smoke_test.py`, and on most of these
sites that works because a fixture is a few hundred bytes of markup. Here the
fixture IS the SSR payload: one product's entry in
`__INITIAL_STATE__.state.data.ichibaSearch.items` is 2-4 KB of JSON on its
own, and a fixture has to carry several of them plus the pagination block and
the page's JSON-LD, or it stops exercising anything the parser is built on.
Pasting that into a Python source file as string literals would make
`smoke_test.py` unreadable and unreviewable. The generated JSON sits beside
it, is regenerated by this script, and is checked by the suite for the same
properties inline fixtures would be.

WHAT YOU NEED TO RUN IT
-----------------------
Your own captures, in `../captures/rakuten/` relative to the repo, named as
the `SOURCES` table below expects. They are deliberately NOT in the
repository: a single listing capture of this site is 0.9-1.5 MB, and a real
page dump carries the session that fetched it.

Take them with `--dump-html`, which writes exactly the bytes the parser was
given. An item page must be saved as RAW BYTES — it is EUC-JP, and a capture
re-saved as UTF-8 is a different file from the one a run sees.

WHAT IT ENFORCES, and why each rule is here
-------------------------------------------
  * every fixture is CUT from a real capture, never hand-written;
  * each one is verified to parse IDENTICALLY to the untrimmed original for
    the products it keeps — every column, not a sample of them. A trim that
    drops the page's JSON-LD silently empties `currency`, and a suite built
    on that fixture would then assert the emptiness as correct;
  * credential-shaped and personal material is replaced with obvious
    placeholders BEFORE anything is embedded, and guarded by PATTERNS rather
    than by the literals one capture happened to contain, so the next
    capture's values are caught too. This site's pages carry three kinds:
      - `apiConfig.ncp.apiKey` and `apiConfig.shipping.apiKey`, two 32-char
        alphanumeric keys baked into EVERY item page. They are Rakuten's own
        front-end keys rather than ours, and they still do not belong in a
        public repo: they read as live credentials to every scanner that
        looks, including this repo's own CI grep;
      - `itemReviewInfo.reviews[]`, which carries a real customer's display
        name and their words. Republishing a person's review is a separate
        act from the site showing it on its own page. The STRUCTURE is what
        the checks need, so the nickname and the text are replaced and
        everything Rakuten generates around them is left untouched;
      - `itemOptions.cpc.qsess`, a per-session id on each sponsored slot;
      - `productUrl`, whose 32-hex catalogue id is public and harmless and
        reads as a credential to every scanner including this repo's own.
"""
import json
import os
import pathlib
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import product_parser as P                                    # noqa: E402

CAPTURES = pathlib.Path(__file__).resolve().parent.parent / "captures" / "rakuten"
OUT = pathlib.Path(__file__).resolve().parent / "fixtures_generated.json"

# The URL each capture was taken from, and the HTTP status it came back with.
# Both are part of the fixture rather than guessed by the suite, because on
# this site the status is load-bearing: the 403 refusal and the 503 throttle
# render the IDENTICAL body and differ only in status, and the Akamai deny
# arrives under 200.
FIXTURE_CONTEXT = {
    "search_p1":         ("https://search.rakuten.co.jp/search/mall/"
                          "%E3%82%B3%E3%83%BC%E3%83%92%E3%83%BC/", 200),
    "search_p1_browser": ("https://search.rakuten.co.jp/search/mall/"
                          "%E3%82%B3%E3%83%BC%E3%83%92%E3%83%BC/", 200),
    "search_lang_en":    ("https://search.rakuten.co.jp/search/mall/"
                          "%E3%82%B3%E3%83%BC%E3%83%92%E3%83%BC/?lang=en", 200),
    "category_p1":       ("https://www.rakuten.co.jp/category/100356/", 200),
    "search_sponsored":  ("https://search.rakuten.co.jp/search/mall/-/551177/",
                          200),
    "search_deep":       ("https://search.rakuten.co.jp/search/mall/-/"
                          "100356/?p=149", 200),
    "search_no_results": ("https://search.rakuten.co.jp/search/mall/"
                          "zzzqqqxyznotathing123/", 200),
    "item_page":         ("https://item.rakuten.co.jp/ajinomoto/"
                          "r4901111371248/", 200),
    "item_discounted":   ("https://item.rakuten.co.jp/sawaicoffee-tea/"
                          "solandluna/", 200),
    # HTTP 200. Not a typo — this is the whole point of the fixture.
    "block_akamai":      ("https://search.rakuten.co.jp/search/mall/"
                          "%E3%82%B3%E3%83%BC%E3%83%92%E3%83%BC/", 200),
    "block_403":         ("https://ranking.rakuten.co.jp/daily/100316/", 403),
    "block_403_browser": ("https://ranking.rakuten.co.jp/daily/100316/", 403),
    "ranking_no_payload": ("https://ranking.rakuten.co.jp/daily/100316/", 200),
}

# name -> (capture file, how many payload products to keep, is it bytes?)
SOURCES = {
    # Listing captures. `keep` is deliberately small but never 1: the parser
    # joins nothing across rows, but a one-row fixture cannot catch an
    # off-by-one in `position` and cannot hold both a reviewed and an
    # unreviewed product.
    "search_p1":            ("search_coffee_p1.html", 6, False),
    "search_p1_browser":    ("search_coffee_p1_browser.html", 6, False),
    "search_lang_en":       ("search_coffee_lang_en.html", 4, False),
    "category_p1":          ("category_100356_p1.html", 6, False),
    # The one that matters most: 52 payload entries of which 7 are sponsored
    # placements. It is the fixture that pins `position` counting emitted
    # rows rather than payload slots.
    "search_sponsored":     ("search_genre_with_sponsored.html", 12, False),
    # A DEEP page — offset 6,660 of a 150-page capped query, which is page
    # 149. Two things only this fixture can exercise: an offset that is not
    # zero (so `served_page_number` is doing real arithmetic rather than
    # returning 1), and a real UNREVIEWED product. The first six rows of any
    # popular query are all reviewed; 9 of 45 on this page are not.
    "search_deep":          ("search_deep_p149.html", 4, False),
    "search_no_results":    ("search_no_results.html", 0, False),
    # Detail pages, kept as bytes because they are EUC-JP.
    "item_page":            ("item_ajinomoto.euc.html", None, True),
    "item_discounted":      ("item_discounted.euc.html", None, True),
    # Refusals, whole — none is over 2 KB.
    "block_akamai":         ("block_akamai_deny.html", None, False),
    "block_403":            ("block_403_branded.html", None, False),
    "block_403_browser":    ("block_403_browser.html", None, False),
    # A route with no payload at all, kept trimmed to its head: proves the
    # classifier does not call a served page content just because the host
    # is Rakuten's.
    "ranking_no_payload":   ("ranking_no_payload.html", None, False),
}

PLACEHOLDER_KEY = "SCRUBBED_FRONTEND_KEY_0000000000"
PLACEHOLDER_NAME = "SCRUBBED_REVIEWER"
PLACEHOLDER_TEXT = "SCRUBBED_REVIEW_TEXT"
PLACEHOLDER_SESSION = "SCRUBBED_SESSION"


def _scrub_obj(node):
    """Replace credential-shaped and personal values in a parsed payload."""
    if isinstance(node, dict):
        out = {}
        for key, value in node.items():
            if key == "apiKey" and isinstance(value, str) and value:
                out[key] = PLACEHOLDER_KEY
            elif key in ("nickName", "userName") and isinstance(value, str):
                out[key] = PLACEHOLDER_NAME
            elif key == "review" and isinstance(value, str):
                out[key] = PLACEHOLDER_TEXT
            elif key == "qsess" and isinstance(value, str):
                out[key] = PLACEHOLDER_SESSION
            elif key == "productUrl" and isinstance(value, str):
                # Rakuten's cross-merchant catalogue id, a 32-hex string in
                # a public URL. Not a credential and not secret — and it
                # trips every scanner that looks for a 32-hex string,
                # including this repo's own CI grep, which would greet a new
                # user with a FAILED line on their first command (§23).
                #
                # Scrubbed rather than allowlisted, because an allowlist
                # that forgives 32-hex inside a rakuten.co.jp URL is a hole
                # a real key could later hide in. Nothing reads this field:
                # `Product` has no column for it, so the fixture loses
                # nothing the checks use.
                out[key] = re.sub(r"[0-9a-f]{32}",
                                  "SCRUBBED_CATALOGUE_ID" + "0" * 11, value)
            else:
                out[key] = _scrub_obj(value)
        return out
    if isinstance(node, list):
        return [_scrub_obj(v) for v in node]
    return node


def _scrub_text(text):
    """The same job on raw markup, for values not inside a parsed payload."""
    text = re.sub(r'(window\.__CHECKOUT_TOKEN__\s*=\s*)"[^"]*"',
                  r'\1"SCRUBBED_TOKEN"', text)
    text = re.sub(r'(window\.__SURF_TOKEN__\s*=\s*)"[^"]*"',
                  r'\1"SCRUBBED_TOKEN"', text)
    return text


def _head_of(text, limit=6000):
    """The document's opening, enough to carry <head> and the asset refs."""
    return text[:limit]


def _minimal_listing(text, keep):
    """A small HTML document carrying this capture's payload, trimmed.

    Keeps the product entries VERBATIM — the whole point is that the fixture
    exercises the same dicts the live payload holds — and keeps the
    pagination block and the JSON-LD untouched, since the first decides the
    end-of-listing check and the second is the only place a listing page
    states a currency.
    """
    state = P.initial_state(text)
    if state is None:
        raise SystemExit("no __INITIAL_STATE__ in the capture")
    payload = ((state.get("state") or {}).get("data") or {}).get("ichibaSearch") or {}
    items = payload.get("items") or []
    trimmed = dict(state)
    inner = dict(trimmed["state"])
    data = dict(inner["data"])
    node = dict(payload)
    kept = list(items[:keep]) if keep else []
    if keep:
        # Plus one UNREVIEWED product, if the capture has one, and this is
        # not padding. Rakuten writes "nobody has rated this" as
        # `{score: 0, numReviews: 0}` rather than as a null, on 28 of 405
        # measured rows — and a zero written through as a rating drags every
        # average a consumer computes. A fixture whose every row happens to
        # be reviewed cannot catch that regression, and the first six rows of
        # a popular query are all reviewed.
        #
        # Still a REAL row from this capture, just not one from the prefix.
        def _unreviewed(hit):
            return (isinstance(hit, dict)
                    and not ((hit.get("review") or {}).get("numReviews")))
        if not any(_unreviewed(h) for h in kept):
            extra = next((h for h in items
                          if _unreviewed(h) and h not in kept), None)
            if extra is not None:
                kept.append(extra)
    node["items"] = kept
    data["ichibaSearch"] = node
    inner["data"] = data
    # Everything else under `state.data` is dropped: it is 200 KB of widgets,
    # related keywords and filter rails that the parser never reads.
    inner["data"] = {"ichibaSearch": node}
    trimmed["state"] = inner
    state_json = json.dumps(_scrub_obj(trimmed), ensure_ascii=False)

    ld = ""
    for block in re.findall(
            r'<script[^>]*type="application/ld\+json"[^>]*>.*?</script>',
            text, re.S):
        ld += block
    # The asset references the positive-served signal counts. Taken from the
    # capture rather than invented, so the fixture is made of the site's own
    # bytes.
    assets = re.findall(r'https://[a-z0-9.]*r10s\.jp/[^"\'\s<>]{0,60}', text)[:4]
    asset_html = "".join('<link rel="preload" href="%s">' % a for a in assets)
    title = re.search(r"<title>(.*?)</title>", text, re.S)
    return (
        "<!DOCTYPE html><html lang=\"ja\"><head><meta charset=\"utf-8\">"
        "<title>%s</title>%s%s</head><body>"
        "<script>window.__INITIAL_STATE__ = %s;</script>"
        "</body></html>" % (
            (title.group(1).strip() if title else "Rakuten"),
            asset_html, ld, state_json))


def _minimal_item(raw):
    """A small document carrying an item page's JSON island, as EUC-JP bytes.

    Returned as text but remembered as EUC-JP in the fixture, because the
    encoding is the point: `decode_page` is the only reason this repo can
    read a detail page from an HTTP client at all, and a fixture that had
    been re-saved as UTF-8 would assert nothing about it.
    """
    text = P.decode_page(raw, "text/html;charset=EUC-JP")
    island = re.search(
        r'<script[^>]*id="item-page-app-data"[^>]*>(.*?)</script>', text, re.S)
    if not island:
        raise SystemExit("no item-page-app-data in the capture")
    data = _scrub_obj(json.loads(island.group(1)))
    # Drop the merchant's own HTML description blobs. They are 30-90 KB of
    # marketing markup that no column in `Product` reads, and keeping them
    # would make the fixture file larger than everything else in the repo
    # put together. Named explicitly rather than pruned by size, so a field
    # the parser DOES read can never be dropped by accident.
    _UNREAD = ("salesDescription", "newProductDescription",
               "itemStaticResource", "shippingCarriers", "featureSectionInfo",
               "layout", "additionalBanner", "makerCreativeInfo",
               "installPaymentInfo", "subscriptionDisclaimer")
    for root in ("newApi", "api"):
        node = data.get(root)
        if root == "api" and isinstance(node, dict):
            node = node.get("data")
        if not isinstance(node, dict):
            continue
        info = node.get("itemInfoSku")
        if isinstance(info, dict):
            for key in _UNREAD:
                info.pop(key, None)
        for key in ("itemStaticResource",):
            node.pop(key, None)
    # The reviews list is kept but SHORTENED: the parser reads only
    # `itemReviewInfo.summary`, and the structure of one scrubbed review is
    # enough for a check that the summary is read rather than the first
    # review's score (a real trap here — a detail page prints three
    # individual `ratingValue` metas before the aggregate one).
    for root in ("newApi", "api"):
        node = data.get(root)
        if root == "api" and isinstance(node, dict):
            node = node.get("data")
        info = (node or {}).get("itemInfoSku") if isinstance(node, dict) else None
        rev = (info or {}).get("itemReviewInfo") if isinstance(info, dict) else None
        if isinstance(rev, dict) and isinstance(rev.get("reviews"), list):
            rev["reviews"] = rev["reviews"][:1]
    # The microdata the detail parser reads for availability and currency,
    # kept verbatim from the capture.
    metas = [m for m in re.findall(r"<meta[^>]+itemprop=\"[^\"]+\"[^>]*>", text)
             if any(k in m for k in ("price", "availability", "sku"))][:12]
    assets = re.findall(r'https://[a-z0-9.]*r10s\.jp/[^"\'\s<>]{0,60}', text)[:4]
    ld = "".join(re.findall(
        r'<script[^>]*type="application/ld\+json"[^>]*>.*?</script>',
        text, re.S))
    title = re.search(r"<title>(.*?)</title>", text, re.S)
    return (
        "<html lang=\"ja\"><head>"
        "<meta http-equiv=\"content-type\" content=\"text/html; charset=EUC-JP\">"
        "<title>%s</title>%s%s%s</head><body>"
        "<script type=\"application/json\" id=\"item-page-app-data\">%s</script>"
        "</body></html>" % (
            (title.group(1).strip() if title else "Rakuten"),
            "".join('<link rel="preload" href="%s">' % a for a in assets),
            "".join(metas), ld,
            json.dumps(data, ensure_ascii=False)))


def _verify_listing(original, fixture, keep, url):
    """The fixture's rows must equal the original's, for the rows it keeps.

    Every column, not a sample. `position` is the one field allowed to
    differ, and only because the trim drops later products — so it is
    compared after re-basing rather than skipped.
    """
    from dataclasses import asdict
    got = P.parse_products(fixture, url)
    # Against the first `len(got)` rows of the original, not its first
    # `keep`: `keep` counts payload ENTRIES and the rows are what survives
    # them. On the sponsored fixture those are 12 and 5, because seven of the
    # entries are paid slots — which is the whole reason that fixture exists.
    want = P.parse_products(original, url)[:len(got)]
    if not got:
        raise SystemExit("fixture parsed no rows at all")
    if len(got) != len(want):
        raise SystemExit("fixture parsed %d rows, the original's matching "
                         "prefix was %d" % (len(got), len(want)))
    for a, b in zip(want, got):
        da, db = asdict(a), asdict(b)
        da.pop("scraped_at"), db.pop("scraped_at")
        if da != db:
            bad = {k: (da[k], db[k]) for k in da if da[k] != db[k]}
            raise SystemExit("fixture row %s differs from the original: %s"
                             % (a.sku, bad))


def main():
    if not CAPTURES.is_dir():
        raise SystemExit(
            "no captures at %s. This script needs your own dumps — see its "
            "docstring. They are not in the repo on purpose." % CAPTURES)
    out = {}
    for name, (filename, keep, as_bytes) in SOURCES.items():
        path = CAPTURES / filename
        if not path.is_file():
            print("  SKIP %-22s (%s not found)" % (name, filename))
            continue
        raw = path.read_bytes()
        if as_bytes:
            html = _minimal_item(raw)
            encoding = "euc_jp"
        else:
            text = _scrub_text(P.decode_page(raw))
            encoding = "utf-8"
            if keep is None:
                html = _head_of(text) if len(text) > 6000 else text
            elif keep == 0:
                html = _minimal_listing(text, 0)
            else:
                html = _minimal_listing(text, keep)
                _verify_listing(text, html, keep,
                                "https://search.rakuten.co.jp/search/mall/x/")
        url, status = FIXTURE_CONTEXT.get(name, ("", 200))
        out[name] = {
            "source": filename,
            "encoding": encoding,
            "bytes_in": len(raw),
            "url": url,
            "status": status,
            "html": html,
        }
        print("  %-22s %8d -> %6d bytes  (%s)"
              % (name, len(raw), len(html), encoding))
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=1),
                   encoding="utf-8")
    print("wrote %s (%d fixtures, %d bytes)"
          % (OUT.name, len(out), OUT.stat().st_size))


if __name__ == "__main__":
    main()
